% extract_weights.m — Export all pre-quantized weights from para_in_mat_FP/ to C arrays
% Output: ulunas_matlab_weights.h + ulunas_matlab_weights.c + qr_config.h + layer_dims.h
% All weights are ALREADY quantized — this script just copies them to C format.

clear; clc;

fp_dir   = fullfile(fileparts(mfilename('fullpath')), '..', 'para_in_mat_FP');
float_dir = fullfile(fileparts(mfilename('fullpath')), '..', 'para_in_mat');
out_dir  = fileparts(mfilename('fullpath'));

addpath(fp_dir);
addpath(float_dir);

%% ====================================================================== %
%% 1. Scan all .mat files
%% ====================================================================== %
files = dir(fullfile(fp_dir, '*.mat'));
fprintf('Found %d .mat weight files\n', length(files));

% Build a struct map: key = C variable name, value = {data, type_str, dims, comment}
weight_map = containers.Map();

for i = 1:length(files)
    fname = files(i).name;
    [~, basename, ~] = fileparts(fname);

    data_struct = load(fullfile(fp_dir, fname));
    var_names = fieldnames(data_struct);
    data = data_struct.(var_names{1});

    % Determine C type from MATLAB class
    if isa(data, 'double') || isa(data, 'single')
        % Double/single — may need to determine signedness
        if all(data(:) >= 0) && max(data(:)) <= 65535
            if max(data(:)) <= 32767
                ctype = 'int16_t';
                mltype = 'int16';
            else
                ctype = 'uint16_t';
                mltype = 'uint16';
            end
        elseif all(data(:) >= -32768 & data(:) <= 32767)
            ctype = 'int16_t';
            mltype = 'int16';
        elseif all(data(:) >= 0 & data(:) <= 4294967295)
            if max(data(:)) <= 2147483647
                ctype = 'int32_t';
                mltype = 'int32';
            else
                ctype = 'uint32_t';
                mltype = 'uint32';
            end
        else
            ctype = 'int32_t';
            mltype = 'int32';
        end
        % Override: running_var always non-negative → force uint16_t
        if contains(basename, '_running_var')
            ctype = 'uint16_t';
            mltype = 'uint16';
        end
        % Convert to integer using MATLAB class name
        data = cast(data, mltype);
    elseif isinteger(data)
        % Already an integer — map MATLAB class to C type
        mltype = class(data);
        switch mltype
            case 'int16'
                ctype = 'int16_t';
            case 'uint16'
                ctype = 'uint16_t';
            case 'int32'
                ctype = 'int32_t';
            case 'uint32'
                ctype = 'uint32_t';
            case 'int64'
                ctype = 'int64_t';
            case 'uint64'
                ctype = 'uint64_t';
            case 'int8'
                ctype = 'int8_t';
            case 'uint8'
                ctype = 'uint8_t';
            otherwise
                error('Unsupported integer type for %s: %s', fname, mltype);
        end
    else
        error('Unknown type for %s: %s', fname, class(data));
    end

    % Create C-safe variable name
    c_name = strrep(strrep(strrep(basename, '.', '_'), '-', '_'), ' ', '_');

    % Determine dims for comment
    dims = size(data);
    dim_str = sprintf('[%s]', strjoin(arrayfun(@num2str, dims, 'UniformOutput', false), '×'));

    % Determine Q format comment based on filename pattern
    q_comment = guess_q_format(basename, ctype, dims);

    % Plan A: GRU HH/IH weights — reload from float, quantize to int32 Q20
    is_gru_w = contains(basename, '_gru_weight_ih_') || contains(basename, '_gru_weight_hh_');
    if is_gru_w
        float_file = fullfile(float_dir, fname);
        if exist(float_file, 'file')
            float_data = load(float_file);
            float_vars = fieldnames(float_data);
            float_vals = double(float_data.(float_vars{1}));
            data = int32(round(float_vals * 1048576));
            ctype = 'int32_t';
            q_comment = 'Q20 (upgraded from Q12)';
        end
    end

    weight_map(c_name) = struct('data', data, 'ctype', ctype, 'dims', dim_str, 'q_comment', q_comment);
end

fprintf('Processed %d weight entries\n', weight_map.Count);

%% ====================================================================== %
%% 2. Generate C header file
%% ====================================================================== %
fid_h = fopen(fullfile(out_dir, 'ulunas_matlab_weights.h'), 'w');
fprintf(fid_h, '/* ulunas_matlab_weights.h — Auto-generated by extract_weights.m */\n');
fprintf(fid_h, '/* %d weight tensors exported from para_in_mat_FP/ */\n', weight_map.Count);
fprintf(fid_h, '#ifndef ULUNAS_MATLAB_WEIGHTS_H\n');
fprintf(fid_h, '#define ULUNAS_MATLAB_WEIGHTS_H\n\n');
fprintf(fid_h, '#include <stdint.h>\n\n');

% Define weight struct types
fprintf(fid_h, '/* Weight tensor descriptors */\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Cin; int Kh; int Kw; } conv_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Cin; } pconv_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Kh; int Kw; } gconv_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Kh; int Kw; } non_gconv_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Cin; } fc_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; int Cin; } gru_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; } bn_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; } ln_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; } affine_weight_t;\n');
fprintf(fid_h, 'typedef struct { const int16_t *data; int Cout; } slope_weight_t;\n');
fprintf(fid_h, 'typedef struct { const uint16_t *data; int Cout; } bn_var_t;\n');
fprintf(fid_h, 'typedef struct { const uint16_t *data; int rows; int cols; } erb_weight_t;\n');
fprintf(fid_h, '\n');

% Declare all weight arrays as extern
keys_list = keys(weight_map);
for i = 1:length(keys_list)
    k = keys_list{i};
    w = weight_map(k);
    fprintf(fid_h, '/* %s %s %s */\n', w.q_comment, w.ctype, w.dims);
    fprintf(fid_h, 'extern const %s %s[%d];\n\n', w.ctype, k, numel(w.data));
end

fprintf(fid_h, '#endif /* ULUNAS_MATLAB_WEIGHTS_H */\n');
fclose(fid_h);
fprintf('Wrote ulunas_matlab_weights.h\n');

%% ====================================================================== %
%% 3. Generate C source file
%% ====================================================================== %
fid_c = fopen(fullfile(out_dir, 'ulunas_matlab_weights.c'), 'w');
fprintf(fid_c, '/* ulunas_matlab_weights.c — Auto-generated by extract_weights.m */\n');
fprintf(fid_c, '#include "ulunas_matlab_weights.h"\n\n');

for i = 1:length(keys_list)
    k = keys_list{i};
    w = weight_map(k);
    total = numel(w.data);

    fprintf(fid_c, '/* %s %s %s */\n', w.q_comment, w.ctype, w.dims);
    fprintf(fid_c, 'const %s %s[%d] = {\n', w.ctype, k, total);

    data_flat = w.data(:);
    for j = 1:total
        if mod(j, 8) == 1
            fprintf(fid_c, '    ');
        end
        if strcmp(w.ctype, 'uint16_t')
            fprintf(fid_c, '%5u', data_flat(j));
        elseif strcmp(w.ctype, 'int16_t')
            fprintf(fid_c, '%6d', data_flat(j));
        elseif strcmp(w.ctype, 'uint32_t')
            fprintf(fid_c, '%10u', data_flat(j));
        else  % int32_t
            fprintf(fid_c, '%11d', data_flat(j));
        end
        if j < total
            fprintf(fid_c, ',');
        end
        if mod(j, 8) == 0
            fprintf(fid_c, '\n');
        end
    end
    if mod(total, 8) ~= 0
        fprintf(fid_c, '\n');
    end
    fprintf(fid_c, '};\n\n');
end
fclose(fid_c);
fprintf('Wrote ulunas_matlab_weights.c\n');

%% ====================================================================== %
%% 4. Generate qr_config.h (from manual extraction of MATLAB source analysis)
%% ====================================================================== %
gen_qr_config(out_dir);
fprintf('Wrote qr_config.h\n');

%% ====================================================================== %
%% 5. Generate layer_dims.h
%% ====================================================================== %
gen_layer_dims(out_dir);
fprintf('Wrote layer_dims.h\n');

fprintf('\n=== Weight extraction complete ===\n');
fprintf('  Weights: %d tensors\n', weight_map.Count);
fprintf('  Output: ulunas_matlab_weights.h, ulunas_matlab_weights.c\n');
fprintf('  Config: qr_config.h, layer_dims.h\n');

%% ====================================================================== %
%% Helper functions
%% ====================================================================== %

function q = guess_q_format(fname, ctype, dims)
    % Guess Q format from filename pattern and data type
    if contains(fname, 'erb_')
        q = 'Q15';  % u16f15
    elseif contains(fname, '_bias') && ~contains(fname, '_running_')
        if contains(fname, 'gru_')
            q = 'Q10';  % s16f10 (GRU bias)
        elseif contains(fname, 'fc_')
            q = 'Q20';  % s32f20
        elseif contains(fname, 'affine_')
            q = 'Q20';  % s32f20
        else
            % Default bias
            if contains(ctype, '32')
                q = 'Q20';
            else
                q = 'Q13';
            end
        end
    elseif contains(fname, '_running_mean')
        q = 'Q20';  % s32f20
    elseif contains(fname, '_running_var')
        q = 'Q11-Q14';  % u16f11-u16f14 (varies by block)
    elseif contains(fname, '_slope')
        q = 'Q13';  % s16f13
    elseif contains(fname, '_weight')
        if contains(fname, 'gru_')
            q = 'Q12';  % s16f12
        elseif contains(fname, 'fc_')
            q = 'Q13';  % s16f13
        elseif contains(fname, 'ln_')
            q = 'Q12';  % s16f12
        elseif contains(fname, 'affine_')
            q = 'Q14';  % s16f14
        elseif contains(fname, 'bn_') || contains(fname, 'ops_2_')
            q = 'Q14';  % s16f14/u16f14
        else
            % Conv/PConv/GConv/TConv weights
            q = 'Q13/Q14';
        end
    else
        q = 'UNKNOWN';
    end
end

function gen_qr_config(out_dir)
    fid = fopen(fullfile(out_dir, 'qr_config.h'), 'w');
    fprintf(fid, '/* qr_config.h — Auto-generated by extract_weights.m */\n');
    fprintf(fid, '/* Qr shift values extracted from MATLAB source code */\n');
    fprintf(fid, '#ifndef QR_CONFIG_H\n');
    fprintf(fid, '#define QR_CONFIG_H\n\n');

    % ===== Encoder Layer 0 (XConv) =====
    fprintf(fid, '/* ── Encoder Layer 0 (XConv) ───────────────────────────────── */\n');
    fprintf(fid, '#define E0_TCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define E0_TCONV_BN_QR1           (-14)\n');
    fprintf(fid, '#define E0_TCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define E0_TCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define E0_TCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define E0_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E0_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E0_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define E0_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E0_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E0_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define E0_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Encoder Layer 1 (XMB0) =====
    fprintf(fid, '/* ── Encoder Layer 1 (XMB0) ────────────────────────────────── */\n');
    fprintf(fid, '#define E1_PCONV0_CONV_QR         (-14)\n');
    fprintf(fid, '#define E1_PCONV0_BN_QR1          (-11)\n');
    fprintf(fid, '#define E1_PCONV0_BN_QR2          (-14)\n');
    fprintf(fid, '#define E1_PCONV0_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define E1_PCONV0_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define E1_TCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define E1_TCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define E1_TCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define E1_TCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define E1_TCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define E1_PCONV1_CONV_QR         (-14)\n');
    fprintf(fid, '#define E1_PCONV1_BN_QR1          (-11)\n');
    fprintf(fid, '#define E1_PCONV1_BN_QR2          (-14)\n');
    fprintf(fid, '#define E1_PCONV1_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define E1_PCONV1_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define E1_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E1_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E1_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define E1_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E1_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E1_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define E1_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Encoder Layer 2 (XDWS0) =====
    fprintf(fid, '/* ── Encoder Layer 2 (XDWS0) ───────────────────────────────── */\n');
    fprintf(fid, '#define E2_PCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define E2_PCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define E2_PCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define E2_PCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define E2_PCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define E2_TCONV_CONV_QR          (-13)\n');
    fprintf(fid, '#define E2_TCONV_BN_QR1           (-14)\n');
    fprintf(fid, '#define E2_TCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define E2_TCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define E2_TCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define E2_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E2_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E2_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define E2_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E2_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E2_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define E2_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Encoder Layer 3 (XMB1) =====
    fprintf(fid, '/* ── Encoder Layer 3 (XMB1) ────────────────────────────────── */\n');
    fprintf(fid, '#define E3_PCONV0_CONV_QR         (-14)\n');
    fprintf(fid, '#define E3_PCONV0_BN_QR1          (-11)\n');
    fprintf(fid, '#define E3_PCONV0_BN_QR2          (-14)\n');
    fprintf(fid, '#define E3_PCONV0_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define E3_PCONV0_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define E3_NONTCONV_CONV_QR       (-13)\n');
    fprintf(fid, '#define E3_NONTCONV_BN_QR1        (-14)\n');
    fprintf(fid, '#define E3_NONTCONV_BN_QR2        (-14)\n');
    fprintf(fid, '#define E3_NONTCONV_AFFINE_QR1    (-13)\n');
    fprintf(fid, '#define E3_NONTCONV_AFFINE_QR2    (-13)\n');
    fprintf(fid, '#define E3_PCONV1_CONV_QR         (-14)\n');
    fprintf(fid, '#define E3_PCONV1_BN_QR1          (-11)\n');
    fprintf(fid, '#define E3_PCONV1_BN_QR2          (-14)\n');
    fprintf(fid, '#define E3_PCONV1_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define E3_PCONV1_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define E3_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E3_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E3_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define E3_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E3_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E3_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define E3_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Encoder Layer 4 (XDWS1) =====
    fprintf(fid, '/* ── Encoder Layer 4 (XDWS1) ───────────────────────────────── */\n');
    fprintf(fid, '#define E4_PCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define E4_PCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define E4_PCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define E4_PCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define E4_PCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define E4_NONTCONV_CONV_QR       (-13)\n');
    fprintf(fid, '#define E4_NONTCONV_BN_QR1        (-14)\n');
    fprintf(fid, '#define E4_NONTCONV_BN_QR2        (-14)\n');
    fprintf(fid, '#define E4_NONTCONV_AFFINE_QR1    (-13)\n');
    fprintf(fid, '#define E4_NONTCONV_AFFINE_QR2    (-13)\n');
    fprintf(fid, '#define E4_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E4_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E4_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define E4_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define E4_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define E4_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define E4_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Decoder Layer 0 (De_XDWS0) =====
    fprintf(fid, '/* ── Decoder Layer 0 (De_XDWS0) ────────────────────────────── */\n');
    fprintf(fid, '#define D0_PCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define D0_PCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define D0_PCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define D0_PCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define D0_PCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define D0_NONTCONV_CONV_QR       (-14)\n');
    fprintf(fid, '#define D0_NONTCONV_BN_QR1        (-14)\n');
    fprintf(fid, '#define D0_NONTCONV_BN_QR2        (-14)\n');
    fprintf(fid, '#define D0_NONTCONV_AFFINE_QR1    (-13)\n');
    fprintf(fid, '#define D0_NONTCONV_AFFINE_QR2    (-13)\n');
    fprintf(fid, '#define D0_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D0_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D0_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define D0_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D0_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D0_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define D0_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Decoder Layer 1 (De_XMB0) =====
    fprintf(fid, '/* ── Decoder Layer 1 (De_XMB0) ─────────────────────────────── */\n');
    fprintf(fid, '#define D1_PCONV0_CONV_QR         (-14)\n');
    fprintf(fid, '#define D1_PCONV0_BN_QR1          (-11)\n');
    fprintf(fid, '#define D1_PCONV0_BN_QR2          (-14)\n');
    fprintf(fid, '#define D1_PCONV0_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define D1_PCONV0_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define D1_NONTCONV_CONV_QR       (-14)\n');
    fprintf(fid, '#define D1_NONTCONV_BN_QR1        (-14)\n');
    fprintf(fid, '#define D1_NONTCONV_BN_QR2        (-14)\n');
    fprintf(fid, '#define D1_NONTCONV_AFFINE_QR1    (-13)\n');
    fprintf(fid, '#define D1_NONTCONV_AFFINE_QR2    (-13)\n');
    fprintf(fid, '#define D1_PCONV1_CONV_QR         (-14)\n');
    fprintf(fid, '#define D1_PCONV1_BN_QR1          (-11)\n');
    fprintf(fid, '#define D1_PCONV1_BN_QR2          (-14)\n');
    fprintf(fid, '#define D1_PCONV1_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define D1_PCONV1_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define D1_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D1_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D1_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define D1_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D1_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D1_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define D1_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Decoder Layer 2 (De_XDWS1) =====
    fprintf(fid, '/* ── Decoder Layer 2 (De_XDWS1) ────────────────────────────── */\n');
    fprintf(fid, '#define D2_PCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define D2_PCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define D2_PCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define D2_PCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define D2_PCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define D2_TCONV_CONV_QR          (-13)\n');
    fprintf(fid, '#define D2_TCONV_BN_QR1           (-14)\n');
    fprintf(fid, '#define D2_TCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define D2_TCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define D2_TCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define D2_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D2_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D2_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define D2_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D2_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D2_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define D2_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Decoder Layer 3 (De_XMB1) =====
    fprintf(fid, '/* ── Decoder Layer 3 (De_XMB1) ─────────────────────────────── */\n');
    fprintf(fid, '#define D3_PCONV0_CONV_QR         (-14)\n');
    fprintf(fid, '#define D3_PCONV0_BN_QR1          (-11)\n');
    fprintf(fid, '#define D3_PCONV0_BN_QR2          (-14)\n');
    fprintf(fid, '#define D3_PCONV0_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define D3_PCONV0_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define D3_TCONV_CONV_QR          (-13)\n');
    fprintf(fid, '#define D3_TCONV_BN_QR1           (-14)\n');
    fprintf(fid, '#define D3_TCONV_BN_QR2           (-14)\n');
    fprintf(fid, '#define D3_TCONV_AFFINE_QR1       (-13)\n');
    fprintf(fid, '#define D3_TCONV_AFFINE_QR2       (-13)\n');
    fprintf(fid, '#define D3_PCONV1_CONV_QR         (-14)\n');
    fprintf(fid, '#define D3_PCONV1_BN_QR1          (-11)\n');
    fprintf(fid, '#define D3_PCONV1_BN_QR2          (-14)\n');
    fprintf(fid, '#define D3_PCONV1_AFFINE_QR1      (-13)\n');
    fprintf(fid, '#define D3_PCONV1_AFFINE_QR2      (-13)\n');
    fprintf(fid, '#define D3_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D3_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D3_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define D3_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D3_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D3_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define D3_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== Decoder Layer 4 (De_XConv) =====
    fprintf(fid, '/* ── Decoder Layer 4 (De_XConv) ────────────────────────────── */\n');
    fprintf(fid, '#define D4_TCONV_CONV_QR          (-14)\n');
    fprintf(fid, '#define D4_TCONV_BN_QR1           (-11)\n');
    fprintf(fid, '#define D4_TCONV_BN_QR2           (-11)\n');
    fprintf(fid, '#define D4_CTFA_TA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D4_CTFA_TA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D4_CTFA_TA_FC_QR          (-8)\n');
    fprintf(fid, '#define D4_CTFA_FA_GRU_QR1        (-21)\n');
    fprintf(fid, '#define D4_CTFA_FA_GRU_QR2        (-16)\n');
    fprintf(fid, '#define D4_CTFA_FA_FC_QR          (-9)\n');
    fprintf(fid, '#define D4_CTFA_ATTN_QR           (-15)\n');
    fprintf(fid, '\n');

    % ===== DPRNN =====
    fprintf(fid, '/* ── GDPRNN ────────────────────────────────────────────────── */\n');
    fprintf(fid, '#define DPRNN_INTRARN_GRU_QR1        (-21)\n');
    fprintf(fid, '#define DPRNN_INTRARN_GRU_QR2        (-16)\n');
    fprintf(fid, '#define DPRNN_INTRARN_FC_QR       (-9)\n');
    fprintf(fid, '#define DPRNN_INTRARN_LN_QR       (-14)\n');
    fprintf(fid, '#define DPRNN_INTERRN_GRU_QR1        (-21)\n');
    fprintf(fid, '#define DPRNN_INTERRN_GRU_QR2        (-16)\n');
    fprintf(fid, '#define DPRNN_INTERRN_FC_QR       (-9)\n');
    fprintf(fid, '#define DPRNN_INTERRN_LN_QR       (-13)\n');
    fprintf(fid, '\n');

    % ===== Global =====
    fprintf(fid, '/* ── Global ────────────────────────────────────────────────── */\n');
    fprintf(fid, '#define Q_GRU_SIG_TANH_QR         (-15)\n');
    fprintf(fid, '#define Q_GRU_HIDDEN_QR           (-15)\n');
    fprintf(fid, '#define Q_CTFA_ATTN_QR            (-15)\n');
    fprintf(fid, '#define Q_BM_BS_QR                (-15)\n');
    fprintf(fid, '#define Q_MASK_QR                 (-15)\n');
    fprintf(fid, '#define Q_LN_VAR_QR               (-11)\n');
    fprintf(fid, '\n');

    fprintf(fid, '#endif /* QR_CONFIG_H */\n');
    fclose(fid);
end

function gen_layer_dims(out_dir)
    fid = fopen(fullfile(out_dir, 'layer_dims.h'), 'w');
    fprintf(fid, '/* layer_dims.h — Auto-generated by extract_weights.m */\n');
    fprintf(fid, '/* Layer dimension macros */\n');
    fprintf(fid, '#ifndef LAYER_DIMS_H\n');
    fprintf(fid, '#define LAYER_DIMS_H\n\n');

    % Input/Output
    fprintf(fid, '/* ── Input / Output ────────────────────────────────────────── */\n');
    fprintf(fid, '#define N_FFT           512\n');
    fprintf(fid, '#define N_FBIN          257\n');
    fprintf(fid, '#define WIN_LEN         512\n');
    fprintf(fid, '#define WIN_INC         256\n');
    fprintf(fid, '#define N_ERB           129\n');
    fprintf(fid, '#define N_ERB_LOW       65\n');
    fprintf(fid, '#define N_ERB_HIGH      64\n');
    fprintf(fid, '#define N_FBIN_HIGH     (N_FBIN - N_ERB_LOW)  /* 192 */\n');
    fprintf(fid, '\n');

    % Encoder
    fprintf(fid, '/* ── Encoder dimensions ────────────────────────────────────── */\n');
    fprintf(fid, '/* Layer 0: XConv */\n');
    fprintf(fid, '#define E0_IN_C         1\n');
    fprintf(fid, '#define E0_IN_W         129\n');
    fprintf(fid, '#define E0_OUT_C        12\n');
    fprintf(fid, '#define E0_OUT_W        65\n');
    fprintf(fid, '#define E0_KH           3\n');
    fprintf(fid, '#define E0_KW           3\n');
    fprintf(fid, '#define E0_STRIDE_H     1\n');
    fprintf(fid, '#define E0_STRIDE_W     2\n');
    fprintf(fid, '#define E0_CACHE_FRAMES  2\n');
    fprintf(fid, '#define E0_TA_GRU_HID   24\n');
    fprintf(fid, '#define E0_FA_GRU_HID   4\n');
    fprintf(fid, '#define E0_FA_NGRP       4\n');
    fprintf(fid, '#define E0_FA_NSEG       17\n');
    fprintf(fid, '#define E0_FA_PADLEN     3\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 1: XMB0 */\n');
    fprintf(fid, '#define E1_IN_C         12\n');
    fprintf(fid, '#define E1_IN_W         65\n');
    fprintf(fid, '#define E1_PCONV0_MID_C  24\n');
    fprintf(fid, '#define E1_PCONV0_GRP    2\n');
    fprintf(fid, '#define E1_PCONV0_GIN_C  6\n');
    fprintf(fid, '#define E1_PCONV0_GOUT_C 12\n');
    fprintf(fid, '#define E1_TCONV_C      24\n');
    fprintf(fid, '#define E1_TCONV_W      33\n');
    fprintf(fid, '#define E1_TCONV_KH     2\n');
    fprintf(fid, '#define E1_TCONV_KW     3\n');
    fprintf(fid, '#define E1_TCONV_SH     1\n');
    fprintf(fid, '#define E1_TCONV_SW     2\n');
    fprintf(fid, '#define E1_PCONV1_MID_C  24\n');
    fprintf(fid, '#define E1_CTFA_TA_HID   48\n');
    fprintf(fid, '#define E1_CTFA_FA_HID   4\n');
    fprintf(fid, '#define E1_CTFA_FA_PAD   2\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 2: XDWS0 */\n');
    fprintf(fid, '#define E2_IN_C         24\n');
    fprintf(fid, '#define E2_IN_W         33\n');
    fprintf(fid, '#define E2_PCONV_MID_C   24\n');
    fprintf(fid, '#define E2_TCONV_C      24\n');
    fprintf(fid, '#define E2_TCONV_W      33\n');
    fprintf(fid, '#define E2_TCONV_KH     2\n');
    fprintf(fid, '#define E2_TCONV_KW     3\n');
    fprintf(fid, '#define E2_TCONV_SH     1\n');
    fprintf(fid, '#define E2_TCONV_SW     1\n');
    fprintf(fid, '#define E2_CTFA_TA_HID   48\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 3: XMB1 */\n');
    fprintf(fid, '#define E3_IN_C         24\n');
    fprintf(fid, '#define E3_IN_W         33\n');
    fprintf(fid, '#define E3_PCONV0_MID_C  32\n');
    fprintf(fid, '#define E3_NONTCONV_C   32\n');
    fprintf(fid, '#define E3_NONTCONV_W   33\n');
    fprintf(fid, '#define E3_NONTCONV_KH  1\n');
    fprintf(fid, '#define E3_NONTCONV_KW  5\n');
    fprintf(fid, '#define E3_PCONV1_MID_C  32\n');
    fprintf(fid, '#define E3_CTFA_TA_HID   64\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 4: XDWS1 */\n');
    fprintf(fid, '#define E4_IN_C         32\n');
    fprintf(fid, '#define E4_IN_W         33\n');
    fprintf(fid, '#define E4_OUT_C        16\n');
    fprintf(fid, '#define E4_PCONV_MID_C   16\n');
    fprintf(fid, '#define E4_NONTCONV_C   16\n');
    fprintf(fid, '#define E4_NONTCONV_W   33\n');
    fprintf(fid, '#define E4_NONTCONV_KH  1\n');
    fprintf(fid, '#define E4_NONTCONV_KW  5\n');
    fprintf(fid, '#define E4_CTFA_TA_HID   32\n');
    fprintf(fid, '\n');

    % Decoder
    fprintf(fid, '/* ── Decoder dimensions ────────────────────────────────────── */\n');
    fprintf(fid, '/* Layer 0: De_XDWS0 */\n');
    fprintf(fid, '#define D0_IN_C         16\n');
    fprintf(fid, '#define D0_IN_W         33\n');
    fprintf(fid, '#define D0_PCONV_MID_C   32\n');
    fprintf(fid, '#define D0_NONTCONV_C   32\n');
    fprintf(fid, '#define D0_NONTCONV_W   33\n');
    fprintf(fid, '#define D0_CTFA_TA_HID   64\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 1: De_XMB0 */\n');
    fprintf(fid, '#define D1_IN_C         32\n');
    fprintf(fid, '#define D1_IN_W         33\n');
    fprintf(fid, '#define D1_OUT_C        24\n');
    fprintf(fid, '#define D1_NONTCONV_C   24\n');
    fprintf(fid, '#define D1_CTFA_TA_HID   48\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 2: De_XDWS1 */\n');
    fprintf(fid, '#define D2_IN_C         24\n');
    fprintf(fid, '#define D2_IN_W         33\n');
    fprintf(fid, '#define D2_TCONV_C      24\n');
    fprintf(fid, '#define D2_CTFA_TA_HID   48\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 3: De_XMB1 */\n');
    fprintf(fid, '#define D3_IN_C         24\n');
    fprintf(fid, '#define D3_IN_W         33\n');
    fprintf(fid, '#define D3_OUT_C        12\n');
    fprintf(fid, '#define D3_OUT_W        65\n');
    fprintf(fid, '#define D3_TCONV_C      12\n');
    fprintf(fid, '#define D3_CTFA_TA_HID   24\n');
    fprintf(fid, '\n');

    fprintf(fid, '/* Layer 4: De_XConv */\n');
    fprintf(fid, '#define D4_IN_C         12\n');
    fprintf(fid, '#define D4_IN_W         65\n');
    fprintf(fid, '#define D4_OUT_C        1  /* verified: TConv Cout=1 */\n');
    fprintf(fid, '#define D4_OUT_W        129\n');
    fprintf(fid, '#define D4_TCONV_KH     3\n');
    fprintf(fid, '#define D4_TCONV_KW     3\n');
    fprintf(fid, '#define D4_TCONV_SH     1\n');
    fprintf(fid, '#define D4_TCONV_SW     2\n');
    fprintf(fid, '#define D4_CACHE_FRAMES  2\n');
    fprintf(fid, '#define D4_CACHE_CHANS  12\n');
    fprintf(fid, '#define D4_CTFA_TA_HID   2\n');
    fprintf(fid, '\n');

    % DPRNN
    fprintf(fid, '/* ── DPRNN dimensions ──────────────────────────────────────── */\n');
    fprintf(fid, '#define DPRNN_CHANNELS   16\n');
    fprintf(fid, '#define DPRNN_TIMESTEPS  33\n');
    fprintf(fid, '#define DPRNN_GROUPS     2\n');
    fprintf(fid, '#define DPRNN_GRP_CH     8\n');
    fprintf(fid, '#define DPRNN_INTRA_HID  4\n');
    fprintf(fid, '#define DPRNN_INTER_HID  8\n');
    fprintf(fid, '#define DPRNN_BIGRU_HID  (DPRNN_INTRA_HID * 2)  /* bidirectional concat */\n');
    fprintf(fid, '\n');

    % State cache sizes
    fprintf(fid, '/* ── State cache sizes (elements) ──────────────────────────── */\n');
    fprintf(fid, '#define CACHE_E0_SIZE    (E0_CACHE_FRAMES * E0_IN_W)\n');
    fprintf(fid, '#define CACHE_E1_SIZE    (E1_TCONV_C * E1_IN_W)\n');
    fprintf(fid, '#define CACHE_E2_SIZE    (E2_TCONV_C * E2_IN_W)\n');
    fprintf(fid, '#define CACHE_D0_SIZE    (D2_TCONV_C * D2_IN_W)\n');
    fprintf(fid, '#define CACHE_D1_SIZE    (D3_TCONV_C * D3_IN_W)\n');
    fprintf(fid, '#define CACHE_D2_SIZE    (D4_CACHE_CHANS * D4_CACHE_FRAMES * D4_IN_W)\n');
    fprintf(fid, '#define CACHE_INTER_SIZE (DPRNN_TIMESTEPS * DPRNN_CHANNELS)\n');
    fprintf(fid, '\n');

    fprintf(fid, '#endif /* LAYER_DIMS_H */\n');
    fclose(fid);
end
