% gen_lut_tables.m — Generate all LUT tables for ulunas_fp.c
% Generates: sigmoid (Q20→Q15), tanh (Q20→Q15), log10 (Q20→Q20)
% Output: ulunas_lut.h + ulunas_lut.c

clear; clc;

%% Config
SIGMOID_LUT_SIZE = 4096;
TANH_LUT_SIZE    = 4096;
LOG10_LUT_SIZE   = 512;

out_dir = fileparts(mfilename('fullpath'));

%% ====================================================================== %
%% 1. Sigmoid LUT: int32_t Q20 → uint16_t Q15
%% ====================================================================== %
% Input range: [-8, 8] in float → [-8*2^20, 8*2^20] = [-8388608, 8388608] in Q20
x_min = -8;
x_max =  8;
x_step = (x_max - x_min) / (SIGMOID_LUT_SIZE - 1);

sigmoid_lut_q15 = zeros(1, SIGMOID_LUT_SIZE);
for i = 1:SIGMOID_LUT_SIZE
    x_float = x_min + (i-1) * x_step;
    y_float = 1.0 / (1.0 + exp(-x_float));
    sigmoid_lut_q15(i) = round(y_float * 32768);  % Q15
end
% Clip to uint16 range
sigmoid_lut_q15 = uint16(max(0, min(65535, sigmoid_lut_q15)));

%% ====================================================================== %
%% 2. Tanh LUT: int32_t Q20 → int16_t Q15
%% ====================================================================== %
x_min = -6;
x_max =  6;
x_step = (x_max - x_min) / (TANH_LUT_SIZE - 1);

tanh_lut_q15 = zeros(1, TANH_LUT_SIZE);
for i = 1:TANH_LUT_SIZE
    x_float = x_min + (i-1) * x_step;
    y_float = tanh(x_float);
    tanh_lut_q15(i) = round(y_float * 32768);  % Q15
end
% Clip to int16 range
tanh_lut_q15 = int16(max(-32768, min(32767, tanh_lut_q15)));

%% ====================================================================== %
%% 3. Log10 LUT: int32_t Q20 → int32_t Q20
%% ====================================================================== %
% Input: positive magnitude in Q20 → float range approx [1e-12, ~100]
% We cover a log-spaced range: index 0→2^-40, index N-1→2^10
% Better to use linear spacing for simplicity:
%   Minimum input ≈ 1.05×10^-6 × 2^20 ≈ 1.1 in Q20 units
%   Maximum input ≈ 100 × 2^20 ≈ 104857600
% Map: use log2-spaced input, linear interpolation on index
% For simplicity: linear spacing in Q20 input range

x_min_q20 = 1;                % ~9.5e-7 in float (below clamped minimum)
x_max_q20 = 8 * 1048576;      % ~8.0 in float (well above typical audio magnitude)
x_step = (x_max_q20 - x_min_q20) / (LOG10_LUT_SIZE - 1);

log10_lut_q20 = zeros(1, LOG10_LUT_SIZE);
for i = 1:LOG10_LUT_SIZE
    x_q20 = x_min_q20 + (i-1) * x_step;
    x_float = double(x_q20) / 1048576.0;
    y_float = log10(max(x_float, 1e-12));
    log10_lut_q20(i) = round(y_float * 1048576);  % Q20
end

%% ====================================================================== %
%% 4. Generate C header file
%% ====================================================================== %
fid_h = fopen(fullfile(out_dir, 'ulunas_lut.h'), 'w');
fprintf(fid_h, '/* ulunas_lut.h — Auto-generated by gen_lut_tables.m */\n');
fprintf(fid_h, '#ifndef ULUNAS_LUT_H\n');
fprintf(fid_h, '#define ULUNAS_LUT_H\n\n');
fprintf(fid_h, '#include <stdint.h>\n\n');
fprintf(fid_h, '#define SIGMOID_LUT_SIZE %d\n', SIGMOID_LUT_SIZE);
fprintf(fid_h, '#define TANH_LUT_SIZE %d\n', TANH_LUT_SIZE);
fprintf(fid_h, '#define LOG10_LUT_SIZE %d\n', LOG10_LUT_SIZE);
fprintf(fid_h, '#define SIGMOID_LUT_X_MIN_Q20  %d     /* -8.0 * 2^20 */\n', int32(-8*2^20));
fprintf(fid_h, '#define SIGMOID_LUT_X_MAX_Q20  %d      /*  8.0 * 2^20 */\n', int32(8*2^20));
fprintf(fid_h, '#define TANH_LUT_X_MIN_Q20     %d     /* %.1f * 2^20 */\n', int32(x_min*2^20), x_min);
fprintf(fid_h, '#define TANH_LUT_X_MAX_Q20     %d      /*  %.1f * 2^20 */\n', int32(x_max*2^20), x_max);
fprintf(fid_h, '#define LOG10_LUT_X_MIN_Q20    %d\n', int32(x_min_q20));
fprintf(fid_h, '#define LOG10_LUT_X_MAX_Q20    %d\n', int32(x_max_q20));
fprintf(fid_h, '\n');
fprintf(fid_h, 'extern const uint16_t sigmoid_lut_q15[SIGMOID_LUT_SIZE];\n');
fprintf(fid_h, 'extern const int16_t  tanh_lut_q15[TANH_LUT_SIZE];\n');
fprintf(fid_h, 'extern const int32_t  log10_lut_q20[LOG10_LUT_SIZE];\n');
fprintf(fid_h, '\n');
fprintf(fid_h, '/* LUT lookup functions */\n');
fprintf(fid_h, 'uint16_t sigmoid_q20_to_q15(int32_t x_q20);\n');
fprintf(fid_h, 'int16_t  tanh_q20_to_q15(int32_t x_q20);\n');
fprintf(fid_h, 'int32_t  log10_q20_to_q20(int32_t x_q20);\n');
fprintf(fid_h, 'uint32_t sqrt_q40_to_q20(uint64_t x_q40);\n');
fprintf(fid_h, '\n');
fprintf(fid_h, '#endif /* ULUNAS_LUT_H */\n');
fclose(fid_h);

%% ====================================================================== %
%% 5. Generate C source file
%% ====================================================================== %
fid_c = fopen(fullfile(out_dir, 'ulunas_lut.c'), 'w');
fprintf(fid_c, '/* ulunas_lut.c — Auto-generated by gen_lut_tables.m */\n');
fprintf(fid_c, '#include "ulunas_lut.h"\n');
fprintf(fid_c, '#include <stdint.h>\n\n');

% Sigmoid LUT
fprintf(fid_c, 'const uint16_t sigmoid_lut_q15[%d] = {\n', SIGMOID_LUT_SIZE);
for i = 1:SIGMOID_LUT_SIZE
    if mod(i, 8) == 1
        fprintf(fid_c, '    ');
    end
    fprintf(fid_c, '%5u', sigmoid_lut_q15(i));
    if i < SIGMOID_LUT_SIZE
        fprintf(fid_c, ', ');
    end
    if mod(i, 8) == 0
        fprintf(fid_c, '\n');
    end
end
fprintf(fid_c, '\n};\n\n');

% Tanh LUT
fprintf(fid_c, 'const int16_t tanh_lut_q15[%d] = {\n', TANH_LUT_SIZE);
for i = 1:TANH_LUT_SIZE
    if mod(i, 8) == 1
        fprintf(fid_c, '    ');
    end
    fprintf(fid_c, '%6d', tanh_lut_q15(i));
    if i < TANH_LUT_SIZE
        fprintf(fid_c, ', ');
    end
    if mod(i, 8) == 0
        fprintf(fid_c, '\n');
    end
end
fprintf(fid_c, '\n};\n\n');

% Log10 LUT
fprintf(fid_c, 'const int32_t log10_lut_q20[%d] = {\n', LOG10_LUT_SIZE);
for i = 1:LOG10_LUT_SIZE
    if mod(i, 8) == 1
        fprintf(fid_c, '    ');
    end
    fprintf(fid_c, '%11d', log10_lut_q20(i));
    if i < LOG10_LUT_SIZE
        fprintf(fid_c, ', ');
    end
    if mod(i, 8) == 0
        fprintf(fid_c, '\n');
    end
end
fprintf(fid_c, '\n};\n\n');

%% LUT lookup functions
fprintf(fid_c, '/* ── Sigmoid: int32_t Q20 → uint16_t Q15 ──────────────────────── */\n');
fprintf(fid_c, 'uint16_t sigmoid_q20_to_q15(int32_t x_q20)\n');
fprintf(fid_c, '{\n');
fprintf(fid_c, '    /* Boundary saturation */\n');
fprintf(fid_c, '    if (x_q20 >= SIGMOID_LUT_X_MAX_Q20) return 32768;   /* 1.0 in Q15 */\n');
fprintf(fid_c, '    if (x_q20 <= SIGMOID_LUT_X_MIN_Q20) return 0;\n');
fprintf(fid_c, '    /* Map to LUT index: x ∈ [-8,8] Q20 → idx ∈ [0, %d] */\n', SIGMOID_LUT_SIZE-1);
fprintf(fid_c, '    int64_t mapped = (int64_t)(x_q20 - SIGMOID_LUT_X_MIN_Q20) * %d;\n', SIGMOID_LUT_SIZE-1);
fprintf(fid_c, '    int32_t idx = (int32_t)(mapped / (SIGMOID_LUT_X_MAX_Q20 - SIGMOID_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    if (idx >= %d) return sigmoid_lut_q15[%d];\n', SIGMOID_LUT_SIZE-1, SIGMOID_LUT_SIZE-1);
fprintf(fid_c, '    /* Linear interpolation */\n');
fprintf(fid_c, '    uint32_t frac = (uint32_t)(mapped %% (SIGMOID_LUT_X_MAX_Q20 - SIGMOID_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    uint32_t denom = (uint32_t)(SIGMOID_LUT_X_MAX_Q20 - SIGMOID_LUT_X_MIN_Q20);\n');
fprintf(fid_c, '    uint32_t y0 = sigmoid_lut_q15[idx];\n');
fprintf(fid_c, '    uint32_t y1 = sigmoid_lut_q15[idx + 1];\n');
fprintf(fid_c, '    return (uint16_t)(y0 + ((y1 - y0) * frac) / denom);\n');
fprintf(fid_c, '}\n\n');

fprintf(fid_c, '/* ── Tanh: int32_t Q20 → int16_t Q15 ─────────────────────────── */\n');
fprintf(fid_c, 'int16_t tanh_q20_to_q15(int32_t x_q20)\n');
fprintf(fid_c, '{\n');
fprintf(fid_c, '    if (x_q20 >= TANH_LUT_X_MAX_Q20) return  32767;   /* 1.0 in Q15 */\n');
fprintf(fid_c, '    if (x_q20 <= TANH_LUT_X_MIN_Q20) return -32768;\n');
fprintf(fid_c, '    int64_t mapped = (int64_t)(x_q20 - TANH_LUT_X_MIN_Q20) * %d;\n', TANH_LUT_SIZE-1);
fprintf(fid_c, '    int32_t idx = (int32_t)(mapped / (TANH_LUT_X_MAX_Q20 - TANH_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    if (idx >= %d) return tanh_lut_q15[%d];\n', TANH_LUT_SIZE-1, TANH_LUT_SIZE-1);
fprintf(fid_c, '    uint32_t frac = (uint32_t)(mapped %% (TANH_LUT_X_MAX_Q20 - TANH_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    uint32_t denom = (uint32_t)(TANH_LUT_X_MAX_Q20 - TANH_LUT_X_MIN_Q20);\n');
fprintf(fid_c, '    int32_t y0 = tanh_lut_q15[idx];\n');
fprintf(fid_c, '    int32_t y1 = tanh_lut_q15[idx + 1];\n');
fprintf(fid_c, '    return (int16_t)(y0 + ((y1 - y0) * (int32_t)frac) / (int32_t)denom);\n');
fprintf(fid_c, '}\n\n');

fprintf(fid_c, '/* ── Log10: int32_t Q20 → int32_t Q20 ────────────────────────── */\n');
fprintf(fid_c, 'int32_t log10_q20_to_q20(int32_t x_q20)\n');
fprintf(fid_c, '{\n');
fprintf(fid_c, '    if (x_q20 <= 0) return log10_lut_q20[0];\n');
fprintf(fid_c, '    if (x_q20 >= LOG10_LUT_X_MAX_Q20) return log10_lut_q20[%d];\n', LOG10_LUT_SIZE-1);
fprintf(fid_c, '    int64_t mapped = (int64_t)(x_q20 - LOG10_LUT_X_MIN_Q20) * %d;\n', LOG10_LUT_SIZE-1);
fprintf(fid_c, '    int32_t idx = (int32_t)(mapped / (LOG10_LUT_X_MAX_Q20 - LOG10_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    if (idx >= %d) return log10_lut_q20[%d];\n', LOG10_LUT_SIZE-1, LOG10_LUT_SIZE-1);
fprintf(fid_c, '    uint32_t frac = (uint32_t)(mapped %% (LOG10_LUT_X_MAX_Q20 - LOG10_LUT_X_MIN_Q20));\n');
fprintf(fid_c, '    uint32_t denom = (uint32_t)(LOG10_LUT_X_MAX_Q20 - LOG10_LUT_X_MIN_Q20);\n');
fprintf(fid_c, '    int64_t y0 = log10_lut_q20[idx];\n');
fprintf(fid_c, '    int64_t y1 = log10_lut_q20[idx + 1];\n');
fprintf(fid_c, '    return (int32_t)(y0 + ((y1 - y0) * (int64_t)frac) / denom);\n');
fprintf(fid_c, '}\n\n');

fprintf(fid_c, '/* ── Sqrt: uint64_t Q40 → uint32_t Q20 (binary search) ──────── */\n');
fprintf(fid_c, 'uint32_t sqrt_q40_to_q20(uint64_t x_q40)\n');
fprintf(fid_c, '{\n');
fprintf(fid_c, '    if (x_q40 == 0) return 0;\n');
fprintf(fid_c, '    /* We need sqrt(x_q40 * 2^(-40)) * 2^20 = sqrt(x_q40) * 2^(-20) * 2^20 = sqrt(x_q40) */\n');
fprintf(fid_c, '    /* Actually: sqrt_q40_to_q20 means x is in Q40 (×2^40), result in Q20 (×2^20) */\n');
fprintf(fid_c, '    /* result = sqrt(x_q40 / 2^40) * 2^20 = sqrt(x_q40) / 2^20 * 2^20 = sqrt(x_q40) */\n');
fprintf(fid_c, '    /* But x_q40 = actual_value * 2^40, so sqrt(actual_value) * 2^20 = sqrt(x_q40 * 2^(-40)) * 2^20 = sqrt(x_q40) */\n');
fprintf(fid_c, '    /* Wait — let us be precise: */\n');
fprintf(fid_c, '    /*   x_float = x_q40 / 2^40 */\n');
fprintf(fid_c, '    /*   result_float = sqrt(x_float) */\n');
fprintf(fid_c, '    /*   result_q20 = result_float * 2^20 */\n');
fprintf(fid_c, '    /*   result_q20 = sqrt(x_q40 / 2^40) * 2^20 */\n');
fprintf(fid_c, '    /*   result_q20 = sqrt(x_q40) / 2^20 * 2^20 = sqrt(x_q40) */\n');
fprintf(fid_c, '    /* So: result_q20 = sqrt(x_q40). No formatting needed. */\n');
fprintf(fid_c, '    /* Binary search for integer sqrt */\n');
fprintf(fid_c, '    uint64_t lo = 0;\n');
fprintf(fid_c, '    uint64_t hi = (uint64_t)1 << 32;  /* sqrt of max Q40 can be up to ~2^31 */\n');
fprintf(fid_c, '    if (hi > 0xFFFFFFFFULL) hi = 0xFFFFFFFFULL;\n');
fprintf(fid_c, '    while (lo < hi) {\n');
fprintf(fid_c, '        uint64_t mid = (lo + hi + 1) >> 1;\n');
fprintf(fid_c, '        if (mid * mid <= x_q40)\n');
fprintf(fid_c, '            lo = mid;\n');
fprintf(fid_c, '        else\n');
fprintf(fid_c, '            hi = mid - 1;\n');
fprintf(fid_c, '    }\n');
fprintf(fid_c, '    return (uint32_t)lo;\n');
fprintf(fid_c, '}\n');

fclose(fid_c);

fprintf('LUT generation complete.\n');
fprintf('  sigmoid: %d entries, range [%d, %d]\n', SIGMOID_LUT_SIZE, min(sigmoid_lut_q15), max(sigmoid_lut_q15));
fprintf('  tanh:    %d entries, range [%d, %d]\n', TANH_LUT_SIZE, min(tanh_lut_q15), max(tanh_lut_q15));
fprintf('  log10:   %d entries, range [%d, %d]\n', LOG10_LUT_SIZE, min(log10_lut_q20), max(log10_lut_q20));
fprintf('Output: ulunas_lut.h + ulunas_lut.c\n');
