/* layer_dims.h — Auto-generated by extract_weights.m */
/* Layer dimension macros */
#ifndef LAYER_DIMS_H
#define LAYER_DIMS_H

/* ── Input / Output ────────────────────────────────────────── */
#define N_FFT           512
#define N_FBIN          257
#define WIN_LEN         512
#define WIN_INC         256
#define N_ERB           129
#define N_ERB_LOW       65
#define N_ERB_HIGH      64
#define N_FBIN_HIGH     (N_FBIN - N_ERB_LOW)  /* 192 */

/* ── Encoder dimensions ────────────────────────────────────── */
/* Layer 0: XConv */
#define E0_IN_C         1
#define E0_IN_W         129
#define E0_OUT_C        12
#define E0_OUT_W        65
#define E0_KH           3
#define E0_KW           3
#define E0_STRIDE_H     1
#define E0_STRIDE_W     2
#define E0_CACHE_FRAMES  2
#define E0_TA_GRU_HID   24
#define E0_FA_GRU_HID   4
#define E0_FA_NGRP       4
#define E0_FA_NSEG       17
#define E0_FA_PADLEN     3

/* Layer 1: XMB0 */
#define E1_IN_C         12
#define E1_IN_W         65
#define E1_PCONV0_MID_C  24
#define E1_PCONV0_GRP    2
#define E1_PCONV0_GIN_C  6
#define E1_PCONV0_GOUT_C 12
#define E1_TCONV_C      24
#define E1_TCONV_W      33
#define E1_TCONV_KH     2
#define E1_TCONV_KW     3
#define E1_TCONV_SH     1
#define E1_TCONV_SW     2
#define E1_PCONV1_MID_C  24
#define E1_CTFA_TA_HID   48
#define E1_CTFA_FA_HID   4
#define E1_CTFA_FA_PAD   2

/* Layer 2: XDWS0 */
#define E2_IN_C         24
#define E2_IN_W         33
#define E2_PCONV_MID_C   24
#define E2_TCONV_C      24
#define E2_TCONV_W      33
#define E2_TCONV_KH     2
#define E2_TCONV_KW     3
#define E2_TCONV_SH     1
#define E2_TCONV_SW     1
#define E2_CTFA_TA_HID   48

/* Layer 3: XMB1 */
#define E3_IN_C         24
#define E3_IN_W         33
#define E3_PCONV0_MID_C  32
#define E3_NONTCONV_C   32
#define E3_NONTCONV_W   33
#define E3_NONTCONV_KH  1
#define E3_NONTCONV_KW  5
#define E3_PCONV1_MID_C  32
#define E3_CTFA_TA_HID   64

/* Layer 4: XDWS1 */
#define E4_IN_C         32
#define E4_IN_W         33
#define E4_OUT_C        16
#define E4_PCONV_MID_C   16
#define E4_NONTCONV_C   16
#define E4_NONTCONV_W   33
#define E4_NONTCONV_KH  1
#define E4_NONTCONV_KW  5
#define E4_CTFA_TA_HID   32

/* ── Decoder dimensions ────────────────────────────────────── */
/* Layer 0: De_XDWS0 */
#define D0_IN_C         16
#define D0_IN_W         33
#define D0_PCONV_MID_C   32
#define D0_NONTCONV_C   32
#define D0_NONTCONV_W   33
#define D0_CTFA_TA_HID   64

/* Layer 1: De_XMB0 */
#define D1_IN_C         32
#define D1_IN_W         33
#define D1_OUT_C        24
#define D1_NONTCONV_C   24
#define D1_CTFA_TA_HID   48

/* Layer 2: De_XDWS1 */
#define D2_IN_C         24
#define D2_IN_W         33
#define D2_TCONV_C      24
#define D2_CTFA_TA_HID   48

/* Layer 3: De_XMB1 */
#define D3_IN_C         24
#define D3_IN_W         33
#define D3_OUT_C        12
#define D3_OUT_W        65
#define D3_TCONV_C      12
#define D3_CTFA_TA_HID   24

/* Layer 4: De_XConv */
#define D4_IN_C         12
#define D4_IN_W         65
#define D4_OUT_C        1  /* verified: TConv Cout=1 */
#define D4_OUT_W        129
#define D4_TCONV_KH     3
#define D4_TCONV_KW     3
#define D4_TCONV_SH     1
#define D4_TCONV_SW     2
#define D4_CACHE_FRAMES  2
#define D4_CACHE_CHANS  12
#define D4_CTFA_TA_HID   2

/* ── DPRNN dimensions ──────────────────────────────────────── */
#define DPRNN_CHANNELS   16
#define DPRNN_TIMESTEPS  33
#define DPRNN_GROUPS     2
#define DPRNN_GRP_CH     8
#define DPRNN_INTRA_HID  4
#define DPRNN_INTER_HID  8
#define DPRNN_BIGRU_HID  (DPRNN_INTRA_HID * 2)  /* bidirectional concat */

/* ── State cache sizes (elements) ──────────────────────────── */
#define CACHE_E0_SIZE    (E0_CACHE_FRAMES * E0_IN_W)
#define CACHE_E1_SIZE    (E1_TCONV_C * E1_IN_W)
#define CACHE_E2_SIZE    (E2_TCONV_C * E2_IN_W)
#define CACHE_D0_SIZE    (D2_TCONV_C * D2_IN_W)
#define CACHE_D1_SIZE    (D3_TCONV_C * D3_IN_W)
#define CACHE_D2_SIZE    (D4_CACHE_CHANS * D4_CACHE_FRAMES * D4_IN_W)
#define CACHE_INTER_SIZE (DPRNN_TIMESTEPS * DPRNN_CHANNELS)

#endif /* LAYER_DIMS_H */
