/* ulunas_lut.h — Auto-generated by gen_lut_tables.m */
#ifndef ULUNAS_LUT_H
#define ULUNAS_LUT_H

#include <stdint.h>

#define SIGMOID_LUT_SIZE 4096
#define TANH_LUT_SIZE 4096
#define LOG10_LUT_SIZE 512
#define SIGMOID_LUT_X_MIN_Q20  -8388608     /* -8.0 * 2^20 */
#define SIGMOID_LUT_X_MAX_Q20  8388608      /*  8.0 * 2^20 */
#define TANH_LUT_X_MIN_Q20     -4194304     /* -4.0 * 2^20 */
#define TANH_LUT_X_MAX_Q20     4194304      /*  4.0 * 2^20 */
#define LOG10_LUT_X_MIN_Q20    1
#define LOG10_LUT_X_MAX_Q20    8388608

extern const uint16_t sigmoid_lut_q15[SIGMOID_LUT_SIZE];
extern const int16_t  tanh_lut_q15[TANH_LUT_SIZE];
extern const int32_t  log10_lut_q20[LOG10_LUT_SIZE];

/* LUT lookup functions */
uint16_t sigmoid_q20_to_q15(int32_t x_q20);
int16_t  tanh_q20_to_q15(int32_t x_q20);
int32_t  log10_q20_to_q20(int32_t x_q20);
uint32_t sqrt_q40_to_q20(uint64_t x_q40);

#endif /* ULUNAS_LUT_H */
