/* ulunas_infer.c — Top-level single-frame inference pipeline
 * Matches Main_infer.m frame-by-frame loop exactly.
 *
 * Pipeline:
 *   STFT → log_gen → BM → Encoder(5层) → GDPRNN×2 → Decoder(5层+skip)
 *   → sigmoid → BS → MASK → ISTFT
 */

#include "ulunas_fp.h"
#include "ulunas_matlab_weights.h"  /* generated by extract_weights.m */

/* External references to encoder/decoder/gdprnn module functions */
extern void encoder_module(
    const int32_t *x,
    int32_t *conv_cache_e0, int16_t *tfa_cache_e0,
    int32_t *conv_cache_e1, int16_t *tfa_cache_e1,
    int32_t *conv_cache_e2, int16_t *tfa_cache_e2,
    int16_t *tfa_cache_e3,
    int16_t *tfa_cache_e4,
    int32_t *y_e0, int32_t *y_e1, int32_t *y_e2,
    int32_t *y_e3, int32_t *y_e4);

extern void gdprnn_module(
    const int32_t *x,
    int16_t *inter_cache,
    int gdprnn_idx,
    int32_t *y);

extern void decoder_module(
    const int32_t *x,
    const int32_t *skip_e4, const int32_t *skip_e3,
    const int32_t *skip_e2, const int32_t *skip_e1, const int32_t *skip_e0,
    int16_t *tfa_cache_d0, int16_t *tfa_cache_d1,
    int32_t *conv_cache_d0, int16_t *tfa_cache_d2,
    int32_t *conv_cache_d1, int16_t *tfa_cache_d3,
    int32_t *conv_cache_d2, int16_t *tfa_cache_d4,
    int32_t *y);

/* ERB weights (from para_in_mat_FP/) */
extern const uint16_t erb_erb_fc_weight[];
extern const uint16_t erb_ierb_fc_weight[];

/* ======================================================================== */
/*  SINGLE-FRAME INFERENCE                                                   */
/* ======================================================================== */

/**
 * ulunas_infer_frame — Process one frame of STFT data
 *
 * @param spec_real     [257] real part of STFT spectrum (float → will be quantized)
 * @param spec_imag     [257] imag part of STFT spectrum
 * @param state         Model state (caches) — updated in place
 * @param y_mask_real   [257] output mask real part (Q20→float after 2^(-20))
 * @param y_mask_imag   [257] output mask imag part
 *
 * NOTE: The caller should quantize spec_real/imag to s32f20 before calling.
 *       The output is in s32f20 format (not dequantized back to float).
 *       The ISTFT should handle the dequantization.
 */
void ulunas_infer_frame(
    const int32_t *spec_real_q20,   /* [257] s32f20 */
    const int32_t *spec_imag_q20,   /* [257] s32f20 */
    ulunas_state_t *state,
    int32_t *y_mask_real,           /* [257] output */
    int32_t *y_mask_imag)           /* [257] output */
{
    /* ── Step 1: Log-magnitude compression ───────────────────────────── */
    int32_t x_log[257];
    for (int i = 0; i < 257; i++) {
        x_log[i] = log_gen_fp(spec_real_q20[i], spec_imag_q20[i]);
    }

    /* ── Step 2: BM (Band Merge) ─────────────────────────────────────── */
    int32_t x_bm[129];
    bm_fp(x_log, erb_erb_fc_weight, x_bm);

    /* ── Step 3: Encoder ─────────────────────────────────────────────── */
    int32_t y_e0[12 * 65];
    int32_t y_e1[24 * 33];
    int32_t y_e2[24 * 33];
    int32_t y_e3[32 * 33];
    int32_t y_e4[16 * 33];

    encoder_module(x_bm,
                   state->conv_cache_e0, state->tfa_cache_e0,
                   state->conv_cache_e1, state->tfa_cache_e1,
                   state->conv_cache_e2, state->tfa_cache_e2,
                   state->tfa_cache_e3,
                   state->tfa_cache_e4,
                   y_e0, y_e1, y_e2, y_e3, y_e4);

    /* ── Step 4: GDPRNN × 2 ──────────────────────────────────────────── */
    int32_t y_rnn1[16 * 33];
    int32_t y_rnn2[16 * 33];

    gdprnn_module(y_e4, state->inter_cache_0, 0, y_rnn1);
    gdprnn_module(y_rnn1, state->inter_cache_1, 1, y_rnn2);

    /* ── Step 5: Decoder ─────────────────────────────────────────────── */
    /* Decoder output: [1, 129] s32f20 (single-channel mask) */
    int32_t y_dec[129];

    decoder_module(y_rnn2,
                   y_e4, y_e3, y_e2, y_e1, y_e0,  /* skip connections */
                   state->tfa_cache_d0, state->tfa_cache_d1,
                   state->conv_cache_d0, state->tfa_cache_d2,
                   state->conv_cache_d1, state->tfa_cache_d3,
                   state->conv_cache_d2, state->tfa_cache_d4,
                   y_dec);

    /* ── Step 6: Sigmoid ─────────────────────────────────────────────── */
    /* y_dec [129] s32f20 → sigmoid → u16f15 [129] */
    uint16_t y_sig[129];
    for (int i = 0; i < 129; i++) {
        y_sig[i] = sigmoid_q20_to_q15(y_dec[i]);
    }

    /* ── Step 7: BS (Band Split) ─────────────────────────────────────── */
    /* y_sig [129] u16f15 → BS → y_bs [257] (single mask) */
    int32_t y_bs[257];
    bs_fp(y_sig, erb_ierb_fc_weight, y_bs);

    /* ── Step 8: MASK ────────────────────────────────────────────────── */
    /* Single mask applied to both real and imag spectra:
     *   y_real = round(spec_real .* y_bs * 2^(-15))
     *   y_imag = round(spec_imag .* y_bs * 2^(-15))
     */
    {
        int32_t round_const = 1 << 14;  /* for 2^(-15) */
        for (int i = 0; i < 257; i++) {
            int64_t pr = (int64_t)spec_real_q20[i] * (int64_t)y_bs[i];
            y_mask_real[i] = (int32_t)((pr + (int64_t)round_const) >> 15);

            int64_t pi = (int64_t)spec_imag_q20[i] * (int64_t)y_bs[i];
            y_mask_imag[i] = (int32_t)((pi + (int64_t)round_const) >> 15);
        }
    }

    /* NOTE: The MATLAB output y_mask = y_q * 2^(-20) dequantizes back to float.
     * In our C pipeline, the ISTFT consumer needs to know the Q format.
     * y_mask_real/imag are in "raw integer" format (not Q20, not Q15).
     * They represent: round(spec_real_Q20 * mask_value * 2^(-15)).
     * spec_real_Q20 = true_value * 2^20
     * mask_value ≈ mask_float
     * y_mask = round(true_value * 2^20 * mask_float * 2^(-15))
     *        = round(true_value * mask_float * 2^5)
     * So y_mask is in Q5 format? Or raw?
     *
     * Actually the MATLAB does: y_mask = y_q * 2^(-20) → float.
     * So y_q is in Q20 format: y_q = round(...).
     * y_mask (float) = y_q / 2^20.
     *
     * For ISTFT, the consumer expects float or properly scaled values.
     * In our fixed-point pipeline, the ISTFT should handle the scaling.
     * For now, we output y_mask as raw int32 and let the ISTFT apply 2^(-20).
     */
}

/* ======================================================================== */
/*  FRAME-LEVEL WRAPPER (for processing an entire audio file)                */
/* ======================================================================== */

/**
 * Process one frame and return complex mask output.
 * This is the equivalent of one iteration of the Main_infer.m frame loop.
 */
void ulunas_process_frame(
    const int32_t *stft_real,      /* [257] s32f20 */
    const int32_t *stft_imag,      /* [257] s32f20 */
    ulunas_state_t *state,
    int32_t *out_real,             /* [257] */
    int32_t *out_imag)             /* [257] */
{
    ulunas_infer_frame(stft_real, stft_imag, state, out_real, out_imag);
}

/* ======================================================================== */
/*  INITIALIZATION                                                           */
/* ======================================================================== */

void ulunas_init(ulunas_state_t *state) {
    ulunas_state_init(state);
}
