/* ulunas_matlab_weights.h — Auto-generated by extract_weights.m */
/* 409 weight tensors exported from para_in_mat_FP/ */
#ifndef ULUNAS_MATLAB_WEIGHTS_H
#define ULUNAS_MATLAB_WEIGHTS_H

#include <stdint.h>

/* Weight tensor descriptors */
typedef struct { const int16_t *data; int Cout; int Cin; int Kh; int Kw; } conv_weight_t;
typedef struct { const int16_t *data; int Cout; int Cin; } pconv_weight_t;
typedef struct { const int16_t *data; int Cout; int Kh; int Kw; } gconv_weight_t;
typedef struct { const int16_t *data; int Cout; int Kh; int Kw; } non_gconv_weight_t;
typedef struct { const int16_t *data; int Cout; int Cin; } fc_weight_t;
typedef struct { const int16_t *data; int Cout; int Cin; } gru_weight_t;
typedef struct { const int16_t *data; int Cout; } bn_weight_t;
typedef struct { const int16_t *data; int Cout; } ln_weight_t;
typedef struct { const int16_t *data; int Cout; } affine_weight_t;
typedef struct { const int16_t *data; int Cout; } slope_weight_t;
typedef struct { const uint16_t *data; int Cout; } bn_var_t;
typedef struct { const uint16_t *data; int rows; int cols; } erb_weight_t;

/* Q20 int32_t [1×32] */
extern const int32_t decoder_de_convs_0_dconv_1_bias[32];

/* Q13/Q14 int16_t [32×1×1×5] */
extern const int16_t decoder_de_convs_0_dconv_1_weight[160];

/* Q20 int32_t [32×1] */
extern const int32_t decoder_de_convs_0_dconv_2_bias[32];

/* Q20 int32_t [32×1] */
extern const int32_t decoder_de_convs_0_dconv_2_running_mean[32];

/* Q11-Q14 uint16_t [32×1] */
extern const uint16_t decoder_de_convs_0_dconv_2_running_var[32];

/* Q13/Q14 int16_t [32×1] */
extern const int16_t decoder_de_convs_0_dconv_2_weight[32];

/* Q20 int32_t [32×33] */
extern const int32_t decoder_de_convs_0_dconv_3_affine_bias[1056];

/* Q14 int16_t [32×33] */
extern const int16_t decoder_de_convs_0_dconv_3_affine_weight[1056];

/* Q13 int16_t [32×1] */
extern const int16_t decoder_de_convs_0_dconv_3_slope_weight[32];

/* Q20 int32_t [1×4] */
extern const int32_t decoder_de_convs_0_dconv_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t decoder_de_convs_0_dconv_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_0_dconv_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_0_dconv_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_0_dconv_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_0_dconv_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_0_dconv_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_0_dconv_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_0_dconv_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_0_dconv_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×32] */
extern const int32_t decoder_de_convs_0_dconv_4_ta_fc_bias[32];

/* Q13 int16_t [64×32] */
extern const int16_t decoder_de_convs_0_dconv_4_ta_fc_weight[2048];

/* Q10 int32_t [1×192] */
extern const int32_t decoder_de_convs_0_dconv_4_ta_gru_bias_hh_l0[192];

/* Q10 int32_t [1×192] */
extern const int32_t decoder_de_convs_0_dconv_4_ta_gru_bias_ih_l0[192];

/* Q12 int16_t [64×192] */
extern const int16_t decoder_de_convs_0_dconv_4_ta_gru_weight_hh_l0[12288];

/* Q12 int16_t [32×192] */
extern const int16_t decoder_de_convs_0_dconv_4_ta_gru_weight_ih_l0[6144];

/* Q20 int32_t [1×32] */
extern const int32_t decoder_de_convs_0_pconv_0_bias[32];

/* Q13/Q14 int16_t [32×8] */
extern const int16_t decoder_de_convs_0_pconv_0_weight[256];

/* Q20 int32_t [32×1] */
extern const int32_t decoder_de_convs_0_pconv_1_bias[32];

/* Q20 int32_t [32×1] */
extern const int32_t decoder_de_convs_0_pconv_1_running_mean[32];

/* Q11-Q14 uint16_t [32×1] */
extern const uint16_t decoder_de_convs_0_pconv_1_running_var[32];

/* Q13/Q14 int16_t [32×1] */
extern const int16_t decoder_de_convs_0_pconv_1_weight[32];

/* Q20 int32_t [32×33] */
extern const int32_t decoder_de_convs_0_pconv_2_affine_bias[1056];

/* Q14 int16_t [32×33] */
extern const int16_t decoder_de_convs_0_pconv_2_affine_weight[1056];

/* Q13 int16_t [32×1] */
extern const int16_t decoder_de_convs_0_pconv_2_slope_weight[32];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_1_dconv_1_bias[24];

/* Q13/Q14 int16_t [24×1×1×5] */
extern const int16_t decoder_de_convs_1_dconv_1_weight[120];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_dconv_2_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_dconv_2_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_1_dconv_2_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t decoder_de_convs_1_dconv_2_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t decoder_de_convs_1_dconv_3_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t decoder_de_convs_1_dconv_3_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t decoder_de_convs_1_dconv_3_slope_weight[24];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_1_pconv1_0_bias[24];

/* Q13/Q14 int16_t [24×16] */
extern const int16_t decoder_de_convs_1_pconv1_0_weight[384];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_pconv1_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_pconv1_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_1_pconv1_1_running_var[24];

/* Q13/Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_1_pconv1_1_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t decoder_de_convs_1_pconv1_2_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t decoder_de_convs_1_pconv1_2_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t decoder_de_convs_1_pconv1_2_slope_weight[24];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_1_pconv2_0_bias[24];

/* Q13/Q14 int16_t [24×12] */
extern const int16_t decoder_de_convs_1_pconv2_0_weight[288];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_pconv2_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_1_pconv2_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_1_pconv2_1_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t decoder_de_convs_1_pconv2_1_weight[24];

/* Q20 int32_t [1×4] */
extern const int32_t decoder_de_convs_1_pconv2_2_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t decoder_de_convs_1_pconv2_2_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_1_pconv2_2_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_1_pconv2_2_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_1_pconv2_2_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_1_pconv2_2_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_1_pconv2_2_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_1_pconv2_2_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_1_pconv2_2_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_1_pconv2_2_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_1_pconv2_2_ta_fc_bias[24];

/* Q13 int16_t [48×24] */
extern const int16_t decoder_de_convs_1_pconv2_2_ta_fc_weight[1152];

/* Q10 int32_t [1×144] */
extern const int32_t decoder_de_convs_1_pconv2_2_ta_gru_bias_hh_l0[144];

/* Q10 int32_t [1×144] */
extern const int32_t decoder_de_convs_1_pconv2_2_ta_gru_bias_ih_l0[144];

/* Q12 int16_t [48×144] */
extern const int16_t decoder_de_convs_1_pconv2_2_ta_gru_weight_hh_l0[6912];

/* Q12 int16_t [24×144] */
extern const int16_t decoder_de_convs_1_pconv2_2_ta_gru_weight_ih_l0[3456];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_2_dconv_1_bias[24];

/* Q13/Q14 int16_t [24×1×2×3] */
extern const int16_t decoder_de_convs_2_dconv_1_weight[144];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_2_dconv_2_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_2_dconv_2_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_2_dconv_2_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t decoder_de_convs_2_dconv_2_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t decoder_de_convs_2_dconv_3_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t decoder_de_convs_2_dconv_3_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t decoder_de_convs_2_dconv_3_slope_weight[24];

/* Q20 int32_t [1×4] */
extern const int32_t decoder_de_convs_2_dconv_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t decoder_de_convs_2_dconv_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_2_dconv_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_2_dconv_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_2_dconv_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_2_dconv_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_2_dconv_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_2_dconv_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_2_dconv_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_2_dconv_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_2_dconv_4_ta_fc_bias[24];

/* Q13 int16_t [48×24] */
extern const int16_t decoder_de_convs_2_dconv_4_ta_fc_weight[1152];

/* Q10 int32_t [1×144] */
extern const int32_t decoder_de_convs_2_dconv_4_ta_gru_bias_hh_l0[144];

/* Q10 int32_t [1×144] */
extern const int32_t decoder_de_convs_2_dconv_4_ta_gru_bias_ih_l0[144];

/* Q12 int16_t [48×144] */
extern const int16_t decoder_de_convs_2_dconv_4_ta_gru_weight_hh_l0[6912];

/* Q12 int16_t [24×144] */
extern const int16_t decoder_de_convs_2_dconv_4_ta_gru_weight_ih_l0[3456];

/* Q20 int32_t [1×24] */
extern const int32_t decoder_de_convs_2_pconv_0_bias[24];

/* Q13/Q14 int16_t [24×12] */
extern const int16_t decoder_de_convs_2_pconv_0_weight[288];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_2_pconv_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t decoder_de_convs_2_pconv_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t decoder_de_convs_2_pconv_1_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t decoder_de_convs_2_pconv_1_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t decoder_de_convs_2_pconv_2_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t decoder_de_convs_2_pconv_2_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t decoder_de_convs_2_pconv_2_slope_weight[24];

/* Q20 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_dconv_1_bias[12];

/* Q13/Q14 int16_t [12×1×2×3] */
extern const int16_t decoder_de_convs_3_dconv_1_weight[72];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_dconv_2_bias[12];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_dconv_2_running_mean[12];

/* Q11-Q14 uint16_t [12×1] */
extern const uint16_t decoder_de_convs_3_dconv_2_running_var[12];

/* Q13/Q14 int16_t [12×1] */
extern const int16_t decoder_de_convs_3_dconv_2_weight[12];

/* Q20 int32_t [12×65] */
extern const int32_t decoder_de_convs_3_dconv_3_affine_bias[780];

/* Q14 int16_t [12×65] */
extern const int16_t decoder_de_convs_3_dconv_3_affine_weight[780];

/* Q13 int16_t [12×1] */
extern const int16_t decoder_de_convs_3_dconv_3_slope_weight[12];

/* Q20 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv1_0_bias[12];

/* Q13/Q14 int16_t [12×12] */
extern const int16_t decoder_de_convs_3_pconv1_0_weight[144];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_pconv1_1_bias[12];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_pconv1_1_running_mean[12];

/* Q11-Q14 uint16_t [12×1] */
extern const uint16_t decoder_de_convs_3_pconv1_1_running_var[12];

/* Q13/Q14 int16_t [12×1] */
extern const int16_t decoder_de_convs_3_pconv1_1_weight[12];

/* Q20 int32_t [12×33] */
extern const int32_t decoder_de_convs_3_pconv1_2_affine_bias[396];

/* Q14 int16_t [12×33] */
extern const int16_t decoder_de_convs_3_pconv1_2_affine_weight[396];

/* Q13 int16_t [12×1] */
extern const int16_t decoder_de_convs_3_pconv1_2_slope_weight[12];

/* Q20 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_0_bias[12];

/* Q13/Q14 int16_t [12×6] */
extern const int16_t decoder_de_convs_3_pconv2_0_weight[72];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_pconv2_1_bias[12];

/* Q20 int32_t [12×1] */
extern const int32_t decoder_de_convs_3_pconv2_1_running_mean[12];

/* Q11-Q14 uint16_t [12×1] */
extern const uint16_t decoder_de_convs_3_pconv2_1_running_var[12];

/* Q13/Q14 int16_t [12×1] */
extern const int16_t decoder_de_convs_3_pconv2_1_weight[12];

/* Q20 int32_t [1×4] */
extern const int32_t decoder_de_convs_3_pconv2_2_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t decoder_de_convs_3_pconv2_2_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_2_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_2_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_2_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_2_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_3_pconv2_2_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_3_pconv2_2_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_3_pconv2_2_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_3_pconv2_2_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×12] */
extern const int32_t decoder_de_convs_3_pconv2_2_ta_fc_bias[12];

/* Q13 int16_t [24×12] */
extern const int16_t decoder_de_convs_3_pconv2_2_ta_fc_weight[288];

/* Q10 int32_t [1×72] */
extern const int32_t decoder_de_convs_3_pconv2_2_ta_gru_bias_hh_l0[72];

/* Q10 int32_t [1×72] */
extern const int32_t decoder_de_convs_3_pconv2_2_ta_gru_bias_ih_l0[72];

/* Q12 int16_t [24×72] */
extern const int16_t decoder_de_convs_3_pconv2_2_ta_gru_weight_hh_l0[1728];

/* Q12 int16_t [12×72] */
extern const int16_t decoder_de_convs_3_pconv2_2_ta_gru_weight_ih_l0[864];

/* Q20 int32_t [1×1] */
extern const int32_t decoder_de_convs_4_ops_1_bias[1];

/* Q13/Q14 int16_t [12×1×3×3] */
extern const int16_t decoder_de_convs_4_ops_1_weight[108];

/* Q20 int32_t [1×1] */
extern const int32_t decoder_de_convs_4_ops_2_bias[1];

/* Q20 int32_t [1×1] */
extern const int32_t decoder_de_convs_4_ops_2_running_mean[1];

/* Q11-Q14 uint16_t [1×1] */
extern const uint16_t decoder_de_convs_4_ops_2_running_var[1];

/* Q14 int16_t [1×1] */
extern const int16_t decoder_de_convs_4_ops_2_weight[1];

/* Q20 int32_t [1×4] */
extern const int32_t decoder_de_convs_4_ops_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t decoder_de_convs_4_ops_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_4_ops_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_4_ops_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_4_ops_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t decoder_de_convs_4_ops_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_4_ops_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_4_ops_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_4_ops_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t decoder_de_convs_4_ops_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×1] */
extern const int32_t decoder_de_convs_4_ops_4_ta_fc_bias[1];

/* Q13 int16_t [2×1] */
extern const int16_t decoder_de_convs_4_ops_4_ta_fc_weight[2];

/* Q10 int32_t [1×6] */
extern const int32_t decoder_de_convs_4_ops_4_ta_gru_bias_hh_l0[6];

/* Q10 int32_t [1×6] */
extern const int32_t decoder_de_convs_4_ops_4_ta_gru_bias_ih_l0[6];

/* Q12 int16_t [2×6] */
extern const int16_t decoder_de_convs_4_ops_4_ta_gru_weight_hh_l0[12];

/* Q12 int16_t [1×6] */
extern const int16_t decoder_de_convs_4_ops_4_ta_gru_weight_ih_l0[6];

/* Q20 int32_t [1×16] */
extern const int32_t dpgrnn_0_inter_fc_bias[16];

/* Q13 int16_t [16×16] */
extern const int16_t dpgrnn_0_inter_fc_weight[256];

/* Q20 int32_t [33×16] */
extern const int32_t dpgrnn_0_inter_ln_bias[528];

/* Q12 int16_t [33×16] */
extern const int16_t dpgrnn_0_inter_ln_weight[528];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_0_inter_rnn_rnn1_bias_hh_l0[24];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_0_inter_rnn_rnn1_bias_ih_l0[24];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_0_inter_rnn_rnn1_weight_hh_l0[192];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_0_inter_rnn_rnn1_weight_ih_l0[192];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_0_inter_rnn_rnn2_bias_hh_l0[24];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_0_inter_rnn_rnn2_bias_ih_l0[24];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_0_inter_rnn_rnn2_weight_hh_l0[192];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_0_inter_rnn_rnn2_weight_ih_l0[192];

/* Q20 int32_t [1×16] */
extern const int32_t dpgrnn_0_intra_fc_bias[16];

/* Q13 int16_t [16×16] */
extern const int16_t dpgrnn_0_intra_fc_weight[256];

/* Q20 int32_t [33×16] */
extern const int32_t dpgrnn_0_intra_ln_bias[528];

/* Q12 int16_t [33×16] */
extern const int16_t dpgrnn_0_intra_ln_weight[528];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn1_bias_hh_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn1_bias_hh_l0_reverse[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn1_bias_ih_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn1_bias_ih_l0_reverse[12];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn1_weight_hh_l0[48];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn1_weight_hh_l0_reverse[48];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn1_weight_ih_l0[96];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn1_weight_ih_l0_reverse[96];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn2_bias_hh_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn2_bias_hh_l0_reverse[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn2_bias_ih_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_0_intra_rnn_rnn2_bias_ih_l0_reverse[12];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn2_weight_hh_l0[48];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn2_weight_hh_l0_reverse[48];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn2_weight_ih_l0[96];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_0_intra_rnn_rnn2_weight_ih_l0_reverse[96];

/* Q20 int32_t [1×16] */
extern const int32_t dpgrnn_1_inter_fc_bias[16];

/* Q13 int16_t [16×16] */
extern const int16_t dpgrnn_1_inter_fc_weight[256];

/* Q20 int32_t [33×16] */
extern const int32_t dpgrnn_1_inter_ln_bias[528];

/* Q12 int16_t [33×16] */
extern const int16_t dpgrnn_1_inter_ln_weight[528];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_1_inter_rnn_rnn1_bias_hh_l0[24];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_1_inter_rnn_rnn1_bias_ih_l0[24];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_1_inter_rnn_rnn1_weight_hh_l0[192];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_1_inter_rnn_rnn1_weight_ih_l0[192];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_1_inter_rnn_rnn2_bias_hh_l0[24];

/* Q20 int32_t [1×24] */
extern const int32_t dpgrnn_1_inter_rnn_rnn2_bias_ih_l0[24];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_1_inter_rnn_rnn2_weight_hh_l0[192];

/* Q13/Q14 int16_t [8×24] */
extern const int16_t dpgrnn_1_inter_rnn_rnn2_weight_ih_l0[192];

/* Q20 int32_t [1×16] */
extern const int32_t dpgrnn_1_intra_fc_bias[16];

/* Q13 int16_t [16×16] */
extern const int16_t dpgrnn_1_intra_fc_weight[256];

/* Q20 int32_t [33×16] */
extern const int32_t dpgrnn_1_intra_ln_bias[528];

/* Q12 int16_t [33×16] */
extern const int16_t dpgrnn_1_intra_ln_weight[528];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn1_bias_hh_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn1_bias_hh_l0_reverse[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn1_bias_ih_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn1_bias_ih_l0_reverse[12];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn1_weight_hh_l0[48];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn1_weight_hh_l0_reverse[48];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn1_weight_ih_l0[96];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn1_weight_ih_l0_reverse[96];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn2_bias_hh_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn2_bias_hh_l0_reverse[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn2_bias_ih_l0[12];

/* Q20 int32_t [1×12] */
extern const int32_t dpgrnn_1_intra_rnn_rnn2_bias_ih_l0_reverse[12];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn2_weight_hh_l0[48];

/* Q13/Q14 int16_t [4×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn2_weight_hh_l0_reverse[48];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn2_weight_ih_l0[96];

/* Q13/Q14 int16_t [8×12] */
extern const int16_t dpgrnn_1_intra_rnn_rnn2_weight_ih_l0_reverse[96];

/* Q20 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_1_bias[12];

/* Q13/Q14 int16_t [12×1×3×3] */
extern const int16_t encoder_en_convs_0_ops_1_weight[108];

/* Q20 int32_t [12×1] */
extern const int32_t encoder_en_convs_0_ops_2_bias[12];

/* Q20 int32_t [12×1] */
extern const int32_t encoder_en_convs_0_ops_2_running_mean[12];

/* Q11-Q14 uint16_t [12×1] */
extern const uint16_t encoder_en_convs_0_ops_2_running_var[12];

/* Q14 int16_t [12×1] */
extern const int16_t encoder_en_convs_0_ops_2_weight[12];

/* Q20 int32_t [12×65] */
extern const int32_t encoder_en_convs_0_ops_3_affine_bias[780];

/* Q14 int16_t [12×65] */
extern const int16_t encoder_en_convs_0_ops_3_affine_weight[780];

/* Q13 int16_t [12×1] */
extern const int16_t encoder_en_convs_0_ops_3_slope_weight[12];

/* Q20 int32_t [1×4] */
extern const int32_t encoder_en_convs_0_ops_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t encoder_en_convs_0_ops_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_0_ops_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_0_ops_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_0_ops_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_0_ops_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×12] */
extern const int32_t encoder_en_convs_0_ops_4_ta_fc_bias[12];

/* Q13 int16_t [24×12] */
extern const int16_t encoder_en_convs_0_ops_4_ta_fc_weight[288];

/* Q10 int32_t [1×72] */
extern const int32_t encoder_en_convs_0_ops_4_ta_gru_bias_hh_l0[72];

/* Q10 int32_t [1×72] */
extern const int32_t encoder_en_convs_0_ops_4_ta_gru_bias_ih_l0[72];

/* Q12 int16_t [24×72] */
extern const int16_t encoder_en_convs_0_ops_4_ta_gru_weight_hh_l0[1728];

/* Q12 int16_t [12×72] */
extern const int16_t encoder_en_convs_0_ops_4_ta_gru_weight_ih_l0[864];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_1_dconv_1_bias[24];

/* Q13/Q14 int16_t [24×1×2×3] */
extern const int16_t encoder_en_convs_1_dconv_1_weight[144];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_dconv_2_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_dconv_2_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_1_dconv_2_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t encoder_en_convs_1_dconv_2_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t encoder_en_convs_1_dconv_3_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t encoder_en_convs_1_dconv_3_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t encoder_en_convs_1_dconv_3_slope_weight[24];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_1_pconv1_0_bias[24];

/* Q13/Q14 int16_t [24×6] */
extern const int16_t encoder_en_convs_1_pconv1_0_weight[144];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_pconv1_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_pconv1_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_1_pconv1_1_running_var[24];

/* Q13/Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_1_pconv1_1_weight[24];

/* Q20 int32_t [24×65] */
extern const int32_t encoder_en_convs_1_pconv1_2_affine_bias[1560];

/* Q14 int16_t [24×65] */
extern const int16_t encoder_en_convs_1_pconv1_2_affine_weight[1560];

/* Q13 int16_t [24×1] */
extern const int16_t encoder_en_convs_1_pconv1_2_slope_weight[24];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_1_pconv2_0_bias[24];

/* Q13/Q14 int16_t [24×12] */
extern const int16_t encoder_en_convs_1_pconv2_0_weight[288];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_pconv2_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_1_pconv2_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_1_pconv2_1_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t encoder_en_convs_1_pconv2_1_weight[24];

/* Q20 int32_t [1×4] */
extern const int32_t encoder_en_convs_1_pconv2_2_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t encoder_en_convs_1_pconv2_2_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_1_pconv2_2_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_1_pconv2_2_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_1_pconv2_2_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_1_pconv2_2_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_1_pconv2_2_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_1_pconv2_2_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_1_pconv2_2_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_1_pconv2_2_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_1_pconv2_2_ta_fc_bias[24];

/* Q13 int16_t [48×24] */
extern const int16_t encoder_en_convs_1_pconv2_2_ta_fc_weight[1152];

/* Q10 int32_t [1×144] */
extern const int32_t encoder_en_convs_1_pconv2_2_ta_gru_bias_hh_l0[144];

/* Q10 int32_t [1×144] */
extern const int32_t encoder_en_convs_1_pconv2_2_ta_gru_bias_ih_l0[144];

/* Q12 int16_t [48×144] */
extern const int16_t encoder_en_convs_1_pconv2_2_ta_gru_weight_hh_l0[6912];

/* Q12 int16_t [24×144] */
extern const int16_t encoder_en_convs_1_pconv2_2_ta_gru_weight_ih_l0[3456];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_2_dconv_1_bias[24];

/* Q13/Q14 int16_t [24×1×2×3] */
extern const int16_t encoder_en_convs_2_dconv_1_weight[144];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_2_dconv_2_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_2_dconv_2_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_2_dconv_2_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t encoder_en_convs_2_dconv_2_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t encoder_en_convs_2_dconv_3_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t encoder_en_convs_2_dconv_3_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t encoder_en_convs_2_dconv_3_slope_weight[24];

/* Q20 int32_t [1×4] */
extern const int32_t encoder_en_convs_2_dconv_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t encoder_en_convs_2_dconv_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_2_dconv_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_2_dconv_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_2_dconv_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_2_dconv_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_2_dconv_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_2_dconv_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_2_dconv_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_2_dconv_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_2_dconv_4_ta_fc_bias[24];

/* Q13 int16_t [48×24] */
extern const int16_t encoder_en_convs_2_dconv_4_ta_fc_weight[1152];

/* Q10 int32_t [1×144] */
extern const int32_t encoder_en_convs_2_dconv_4_ta_gru_bias_hh_l0[144];

/* Q10 int32_t [1×144] */
extern const int32_t encoder_en_convs_2_dconv_4_ta_gru_bias_ih_l0[144];

/* Q12 int16_t [48×144] */
extern const int16_t encoder_en_convs_2_dconv_4_ta_gru_weight_hh_l0[6912];

/* Q12 int16_t [24×144] */
extern const int16_t encoder_en_convs_2_dconv_4_ta_gru_weight_ih_l0[3456];

/* Q20 int32_t [1×24] */
extern const int32_t encoder_en_convs_2_pconv_0_bias[24];

/* Q13/Q14 int16_t [24×12] */
extern const int16_t encoder_en_convs_2_pconv_0_weight[288];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_2_pconv_1_bias[24];

/* Q20 int32_t [24×1] */
extern const int32_t encoder_en_convs_2_pconv_1_running_mean[24];

/* Q11-Q14 uint16_t [24×1] */
extern const uint16_t encoder_en_convs_2_pconv_1_running_var[24];

/* Q13/Q14 int16_t [24×1] */
extern const int16_t encoder_en_convs_2_pconv_1_weight[24];

/* Q20 int32_t [24×33] */
extern const int32_t encoder_en_convs_2_pconv_2_affine_bias[792];

/* Q14 int16_t [24×33] */
extern const int16_t encoder_en_convs_2_pconv_2_affine_weight[792];

/* Q13 int16_t [24×1] */
extern const int16_t encoder_en_convs_2_pconv_2_slope_weight[24];

/* Q20 int32_t [1×32] */
extern const int32_t encoder_en_convs_3_dconv_1_bias[32];

/* Q13/Q14 int16_t [32×1×1×5] */
extern const int16_t encoder_en_convs_3_dconv_1_weight[160];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_dconv_2_bias[32];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_dconv_2_running_mean[32];

/* Q11-Q14 uint16_t [32×1] */
extern const uint16_t encoder_en_convs_3_dconv_2_running_var[32];

/* Q13/Q14 int16_t [32×1] */
extern const int16_t encoder_en_convs_3_dconv_2_weight[32];

/* Q20 int32_t [32×33] */
extern const int32_t encoder_en_convs_3_dconv_3_affine_bias[1056];

/* Q14 int16_t [32×33] */
extern const int16_t encoder_en_convs_3_dconv_3_affine_weight[1056];

/* Q13 int16_t [32×1] */
extern const int16_t encoder_en_convs_3_dconv_3_slope_weight[32];

/* Q20 int32_t [1×32] */
extern const int32_t encoder_en_convs_3_pconv1_0_bias[32];

/* Q13/Q14 int16_t [32×12] */
extern const int16_t encoder_en_convs_3_pconv1_0_weight[384];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_pconv1_1_bias[32];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_pconv1_1_running_mean[32];

/* Q11-Q14 uint16_t [32×1] */
extern const uint16_t encoder_en_convs_3_pconv1_1_running_var[32];

/* Q13/Q14 int16_t [32×1] */
extern const int16_t encoder_en_convs_3_pconv1_1_weight[32];

/* Q20 int32_t [32×33] */
extern const int32_t encoder_en_convs_3_pconv1_2_affine_bias[1056];

/* Q14 int16_t [32×33] */
extern const int16_t encoder_en_convs_3_pconv1_2_affine_weight[1056];

/* Q13 int16_t [32×1] */
extern const int16_t encoder_en_convs_3_pconv1_2_slope_weight[32];

/* Q20 int32_t [1×32] */
extern const int32_t encoder_en_convs_3_pconv2_0_bias[32];

/* Q13/Q14 int16_t [32×16] */
extern const int16_t encoder_en_convs_3_pconv2_0_weight[512];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_pconv2_1_bias[32];

/* Q20 int32_t [32×1] */
extern const int32_t encoder_en_convs_3_pconv2_1_running_mean[32];

/* Q11-Q14 uint16_t [32×1] */
extern const uint16_t encoder_en_convs_3_pconv2_1_running_var[32];

/* Q13/Q14 int16_t [32×1] */
extern const int16_t encoder_en_convs_3_pconv2_1_weight[32];

/* Q20 int32_t [1×4] */
extern const int32_t encoder_en_convs_3_pconv2_2_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t encoder_en_convs_3_pconv2_2_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_3_pconv2_2_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_3_pconv2_2_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_3_pconv2_2_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_3_pconv2_2_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_3_pconv2_2_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_3_pconv2_2_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_3_pconv2_2_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_3_pconv2_2_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×32] */
extern const int32_t encoder_en_convs_3_pconv2_2_ta_fc_bias[32];

/* Q13 int16_t [64×32] */
extern const int16_t encoder_en_convs_3_pconv2_2_ta_fc_weight[2048];

/* Q10 int32_t [1×192] */
extern const int32_t encoder_en_convs_3_pconv2_2_ta_gru_bias_hh_l0[192];

/* Q10 int32_t [1×192] */
extern const int32_t encoder_en_convs_3_pconv2_2_ta_gru_bias_ih_l0[192];

/* Q12 int16_t [64×192] */
extern const int16_t encoder_en_convs_3_pconv2_2_ta_gru_weight_hh_l0[12288];

/* Q12 int16_t [32×192] */
extern const int16_t encoder_en_convs_3_pconv2_2_ta_gru_weight_ih_l0[6144];

/* Q20 int32_t [1×16] */
extern const int32_t encoder_en_convs_4_dconv_1_bias[16];

/* Q13/Q14 int16_t [16×1×1×5] */
extern const int16_t encoder_en_convs_4_dconv_1_weight[80];

/* Q20 int32_t [16×1] */
extern const int32_t encoder_en_convs_4_dconv_2_bias[16];

/* Q20 int32_t [16×1] */
extern const int32_t encoder_en_convs_4_dconv_2_running_mean[16];

/* Q11-Q14 uint16_t [16×1] */
extern const uint16_t encoder_en_convs_4_dconv_2_running_var[16];

/* Q13/Q14 int16_t [16×1] */
extern const int16_t encoder_en_convs_4_dconv_2_weight[16];

/* Q20 int32_t [16×33] */
extern const int32_t encoder_en_convs_4_dconv_3_affine_bias[528];

/* Q14 int16_t [16×33] */
extern const int16_t encoder_en_convs_4_dconv_3_affine_weight[528];

/* Q13 int16_t [16×1] */
extern const int16_t encoder_en_convs_4_dconv_3_slope_weight[16];

/* Q20 int32_t [1×4] */
extern const int32_t encoder_en_convs_4_dconv_4_fa_fc_bias[4];

/* Q13 int16_t [8×4] */
extern const int16_t encoder_en_convs_4_dconv_4_fa_fc_weight[32];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_4_dconv_4_fa_gru_bias_hh_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_4_dconv_4_fa_gru_bias_hh_l0_reverse[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_4_dconv_4_fa_gru_bias_ih_l0[12];

/* Q10 int32_t [1×12] */
extern const int32_t encoder_en_convs_4_dconv_4_fa_gru_bias_ih_l0_reverse[12];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_4_dconv_4_fa_gru_weight_hh_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_4_dconv_4_fa_gru_weight_hh_l0_reverse[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_4_dconv_4_fa_gru_weight_ih_l0[48];

/* Q12 int16_t [4×12] */
extern const int16_t encoder_en_convs_4_dconv_4_fa_gru_weight_ih_l0_reverse[48];

/* Q20 int32_t [1×16] */
extern const int32_t encoder_en_convs_4_dconv_4_ta_fc_bias[16];

/* Q13 int16_t [32×16] */
extern const int16_t encoder_en_convs_4_dconv_4_ta_fc_weight[512];

/* Q10 int32_t [1×96] */
extern const int32_t encoder_en_convs_4_dconv_4_ta_gru_bias_hh_l0[96];

/* Q10 int32_t [1×96] */
extern const int32_t encoder_en_convs_4_dconv_4_ta_gru_bias_ih_l0[96];

/* Q12 int16_t [32×96] */
extern const int16_t encoder_en_convs_4_dconv_4_ta_gru_weight_hh_l0[3072];

/* Q12 int16_t [16×96] */
extern const int16_t encoder_en_convs_4_dconv_4_ta_gru_weight_ih_l0[1536];

/* Q20 int32_t [1×16] */
extern const int32_t encoder_en_convs_4_pconv_0_bias[16];

/* Q13/Q14 int16_t [16×16] */
extern const int16_t encoder_en_convs_4_pconv_0_weight[256];

/* Q20 int32_t [16×1] */
extern const int32_t encoder_en_convs_4_pconv_1_bias[16];

/* Q20 int32_t [16×1] */
extern const int32_t encoder_en_convs_4_pconv_1_running_mean[16];

/* Q11-Q14 uint16_t [16×1] */
extern const uint16_t encoder_en_convs_4_pconv_1_running_var[16];

/* Q13/Q14 int16_t [16×1] */
extern const int16_t encoder_en_convs_4_pconv_1_weight[16];

/* Q20 int32_t [16×33] */
extern const int32_t encoder_en_convs_4_pconv_2_affine_bias[528];

/* Q14 int16_t [16×33] */
extern const int16_t encoder_en_convs_4_pconv_2_affine_weight[528];

/* Q13 int16_t [16×1] */
extern const int16_t encoder_en_convs_4_pconv_2_slope_weight[16];

/* Q15 uint16_t [192×64] */
extern const uint16_t erb_erb_fc_weight[12288];

/* Q15 uint16_t [64×192] */
extern const uint16_t erb_ierb_fc_weight[12288];

#endif /* ULUNAS_MATLAB_WEIGHTS_H */
